name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: npm install, build, and test
      run: |
        npm i
        npm run build
      env:
        CI: true
  
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_CHANNEL: github-actions-channel
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
