name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: npm install, build, and test
      run: |
        npm i
        npm run build
      env:
        CI: true
  
    - name: action-slack
      uses: 8398a7/action-slack@v2.4.2
      with:
        status: ${{ job.status }}
        text: 'test integration'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
